### ISSUE TITLE
The connector file is not up to date

### ISSUE THREAD

**Issue by trymzet** [pichlerpa/PowerBITrinoConnector#14]
Hi, it seems that the .mez file was not recompiled after the last feature was added (https://github.com/pichlerpa/PowerBITrinoConnector/pull/11)

I tried compiling it myself as per `README.md`, but got this:

```console
 *  Executing task: c:\Users\micha\.vscode\extensions\powerquery.vscode-powerquery-sdk-0.2.3-win32-x64\.nuget\Microsoft.PowerQuery.SdkTools.2.114.4\tools\MakePQX.exe compile 

Unexpected exception:
System.IO.FileNotFoundException: Could not find file 'C:\Users\micha\PowerBITrinoConnector\Trino\C%EF%80%BA%EF%81%9CUsers%EF%81%9Cmicha%EF%81%9CAppData%EF%81%9CLocal%EF%81%9Cvscode-sqltools%EF%81%9CData%EF%81%9C.node-runtime'.
File name: 'C:\Users\micha\PowerBITrinoConnector\Trino\C%EF%80%BA%EF%81%9CUsers%EF%81%9Cmicha%EF%81%9CAppData%EF%81%9CLocal%EF%81%9Cvscode-sqltools%EF%81%9CData%EF%81%9C.node-runtime'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.DoCreateEntryFromFile(ZipArchive destination, String sourceFileName, String entryName, Nullable`1 compressionLevel)
   at MakePQX.Tasks.TaskStash.<>c__DisplayClass2_0.<BuildMezProject>b__0(String oneRelativePath)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at MakePQX.Tasks.TaskStash.BuildMezProject(String nullableProjectDirectory, String directoryName, String fileName)
   at Microsoft.Mashup.MakePQX.Program.<>c__DisplayClass4_1.<Main>b__5()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.Mashup.MakePQX.Program.Main(String[] args)

 *  The terminal process "c:\Users\micha\.vscode\extensions\powerquery.vscode-powerquery-sdk-0.2.3-win32-x64\.nuget\Microsoft.PowerQuery.SdkTools.2.114.4\tools\MakePQX.exe 'compile'" terminated with exit code: 4294967286. 
 *  Terminal will be reused by tasks, press any key to close it
```

**Comment by pichlerpa** [comment]
@trymzet you need to open the "Trino" folder within VS for the compilation to work as outlined in step 2.

**Comment by pichlerpa** [comment]
The compiled MEZ includes now the last changes from https://github.com/pichlerpa/PowerBITrinoConnector/commit/4ef9df47655facbff1c5b0309c8c299f1a3a6788 and is up-to-date.
